# ..travis.yml
dist: trusty

sudo: required

language: python
python: 3.6

matrix:
    include:
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36

before_install: 'pip install --upgrade pip'

install: 'pip install tox'

script:
    - 'tox'

