# ..travis.yml
dist: trusty

sudo: required

language: python
python: 3.6

before_install:
  - pip install --upgrade pip

install:
  - pip install -e .["docs","tests"] -q

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      script:
      - python setup.py test || if [ $? -eq 1 -o $? -eq 5 ]; then exit 0 ;  fi;
      name: "test"
    - script:
      - python setup.py lint || exit $(($? & 35))
      name: "lint"
    - script:
      - python setup.py sdist
      name: "build"
    - stage: deploy
      script:
      - sphinx-build docs/ build/